version: '3.8'

services:
  # MySQL Database (Development)
  mysql:
    image: mysql:8.0
    container_name: securewallet_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: securewallet_dev
      MYSQL_USER: securewallet_dev
      MYSQL_PASSWORD: securewalletpass_dev
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - securewallet_network_dev

  # MongoDB Database (Development)
  mongodb:
    image: mongo:7.0
    container_name: securewallet_mongodb_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: wallet_app_dev
    ports:
      - "27018:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - securewallet_network_dev

  # Redis Cache (Development)
  redis:
    image: redis:7.2-alpine
    container_name: securewallet_redis_dev
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - securewallet_network_dev

  # Backend Application (Development)
  backend:
    build: .
    container_name: securewallet_backend_dev
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    command: uvicorn src.app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - mysql
      - mongodb
      - redis
    networks:
      - securewallet_network_dev

  # Frontend Application (Development)
  frontend:
    build: ./frontend
    container_name: securewallet_frontend_dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8001/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm run dev
    depends_on:
      - backend
    networks:
      - securewallet_network_dev

volumes:
  mysql_dev_data:
  mongodb_dev_data:
  redis_dev_data:

networks:
  securewallet_network_dev:
    driver: bridge
